# Generated by Django 5.0.4 on 2024-07-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInscription', '0002_membres_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membres',
            name='user',
        ),
    ]
