# Generated by Django 5.0.3 on 2024-04-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apphome', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
