# Generated by Django 5.0.4 on 2024-05-11 12:36

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apphome', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=30, prefix='cat', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(upload_to='static/img/prods'),
        ),
    ]
