# Generated by Django 5.0.4 on 2024-06-11 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInscription', '0001_initial'),
        ('Apphome', '0006_productreview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppInscription.membres'),
            preserve_default=False,
        ),
    ]
